### PR TITLE
Some keyboard shortcuts

### PR DESCRIPTION
**Pull request by boblemarin**
Just added a keydown listener to use the space bar and the left/right keys.
Also fixed a small problem when scrolling back to the beginning with the button.

### CODE REVIEW

**Comment by minghai** [comment]
Hi, Boblemarin!
Thank you for your patch! and please excuse me for taking a long time for responding.

I want to merge your patch No.1 and No.3. (Trailing spaces and Left/Right buttons handlers).
I also have a plan to support keyboards, but I think we have to have a grand design  before implementing some.
My image of keyboard plan is vi-like mode change from mouse-mode.
After changing from the mouse mode, you can do everything with keyboard. And I want to
control red cursor with vi keymap. Maybe many of you don't like it. :-)

I don't know about GitHub very well, so could you please tell me is there a way to merge
some of your patches with GitHub so that GitHub admits this as your contribute?
If not, could you please divide your pull request into 3 pieces so that I can merge which I like?
And by the way, what kind of problem did you have and solved with No.3 patch?

Thanks!

**Comment by boblemarin** [comment]
About the scroll fix, here's how to reproduce the problem :
- put some note
- press play
- when the score has scrolled a bit, press stop
- try to rewind the score with the left arrow button, it often stops before displaying the key on the left side of the score. 

I'm not sure that I can remove one commit from this pull request, we might have to close it and make new ones...

**Comment by minghai** [comment]
HI!
Thanks for your bug description. I could reproduce it with just one try.

I'm glad if you could put another pull request for this. If that's too much trouble for you and you don't
mind if I apply the patch by hand, I will do it by myself. (But in that case, I'm afraid that GitHub
won't record that that was your contribution.)

In the case that I should have to close this first, I close this once. Please give me a comment or
reopen this if you need to do so.

Thanks!

**Comment by boblemarin** [comment]
Well, let's keep it simple. Just apply the fix yourself for the scroll issue (around line 1440). The cleaning of trailing spaces is just an automatic process in my editor, I couldn't avoid it.
For the keyboard support, I'll keep my fork as I just wanted that feature to be able to use your wonderful work a little bit more easily.
And thanks for sharing.

**Comment by minghai** [comment]
Hi.
Sorry for no development for a long time, and I recently get to think that I should have commit
anyway and then made any changes.
So I'll try reopen this and try to merge this pull request. I'm sorry if I bother you.

I've been developing MIDI support for this little program. Now it can play 16ch, 128 program, 64 poly sounds , but it still needs some little trick to send key off to stop playing cause some MIDI sounds
doesn't stop playing automatically. I'm searching easiest way to specify note length, or put note off
on the score. I will use keyboard input for that purpose.

I'll release that new version soon. It might be separate project since it needs "specific" MIDI output.

Please ignore post. Thanks. :-)

**Pull request merged**
